sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t os1979/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true os1979/docker-react npm run test -- --coverage

before_deploy: "echo 'ready?'"

deploy:
  provider: elasticbeanstalk
  access_key_id: 
    secure: "AKIA34PMKKNQ5YTND7XN"
  secret_access_key:
    secure: "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"
  region: 'us-east-1'
  app: 'react'
  env: 'React-env'
  bucket_name: 'elasticbeanstalk-eu-central-1-817076261729'
  bucket_path: 'react'
  on:
    branch: main

