sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t os1979/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true os1979/docker-react npm run test -- --coverage

before_deploy: "echo 'ready!!!?'"

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: 'eu-central-1'
  app: 'travis'
  env: 'Travis-env'
  bucket_name: 'elasticbeanstalk-eu-central-1-817076261729'
  bucket_path: 'travis'
  on:
    branch: main

